# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## This Cloud Build script configures other Cloud Build triggers for
## various build actions associated with this repository.

steps:
- name: 'google/cloud-sdk:slim'
  id: Configure build triggers
  entrypoint: /bin/bash
  # TODO(#98): Use Deployment Manager to configure the triggers
  args:
  - -c
  - |
    set -o errexit
    set -o xtrace
    for f in .github/infra/triggers/*.yaml
    do
      trigger_filename=$${f##*/}
      trigger_name=$${trigger_filename%.*} 
      gcloud beta builds triggers delete --quiet $${trigger_name} || true
      gcloud beta builds triggers import --source $$f
    done