# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## The steps in this Cloud Build script build and deploy the backend service

steps:
# build the backend Node service and deploy it to Cloud Run for Anthos
- name: node:12.16
  id: Prepare
  entrypoint: npm
  args: ['ci']
  dir: 'backend/user-service'
- name: node:12.16
  id: Build
  entrypoint: npm
  args: ['run', 'build']
  dir: 'backend/user-service'
- name: 'gcr.io/cloud-builders/docker'
  id: Build Docker Image
  dir: 'backend/user-service'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_USER_SVC_IMAGE}:${BUILD_ID}', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args: ['push', 'gcr.io/$PROJECT_ID/${_USER_SVC_IMAGE}']
- name: 'google/cloud-sdk:latest'
  id: Deploy
  args: ['gcloud', 'alpha', 'run', 'deploy', '${_USER_SVC_NAME}',
         '--image', 'gcr.io/$PROJECT_ID/${_USER_SVC_IMAGE}:${BUILD_ID}',
         '--platform', 'gke',
         '--cluster', '${_CLUSTER_NAME}',
         '--cluster-location', '${_CLUSTER_LOCATION}',
         '--connectivity', 'external',
         '--namespace', '${_NAMESPACE}',
         '--service-account', '${_USER_SVC_KSA}',
         '--set-env-vars=GOOGLE_CLOUD_PROJECT=${PROJECT_ID}',
        ]
images: ['gcr.io/$PROJECT_ID/${_USER_SVC_IMAGE}']
