name: "PR Validation"

on:
  pull_request:
    branches: [ master ]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install markdown lint
      run: gem install mdl

    - name: Run markdown lint
      run: mdl $GITHUB_WORKSPACE

  lint-webui:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.16.2'
    - working-directory: ./webui
      run: npm ci
    - working-directory: ./webui
      run: npm run lint

  npm-audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.16.2'
    - working-directory: ./webui
      run: npm audit
  
  backend-lint:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.13'
    - id: gofmt
      run: |
        GOFMT_OUT=$(gofmt -l ./backend/src)
        if [ -z "${GOFMT_OUT}" ]
        then
          echo "All files formatted correctly!"
        else
          gofmt -d ./backend/src
          exit 1
        fi
